---
steps:
  - type: "waiter"

  - name: ":mag: :fist:"
    command: "docker-compose run --rm build bin/no-only"

  - wait

  - name: ":nodejs: Test It"
    command: "docker-compose run --rm build bin/test"

  - name: ":nodejs: Lint It"
    command: "docker-compose run --rm build bin/lint"

  - wait

  - name: ":shipit: Deploy Styleguide"
    command: "docker-compose run --rm build bin/only-for-version-releases bin/deploy-docs"
    branches: master

  - name: ":shipit: Deploy NPM Package"
    command: "docker-compose run --rm build bin/only-for-version-releases bin/deploy"
    branches: master

  - wait

  - name: ":loudspeaker: Announce It"
    command: "docker-compose run --rm build bin/only-for-version-releases bin/announce"
    branches: master
