---
steps:
  - type: "waiter"

  - name: ":nodejs: Test It"
    command: "docker-compose run --rm build bin/test"
    agents:
      queue: elastic

  - wait

  - name: ":shipit: Deploy Styleguide"
    command: "docker-compose run --rm build bin/deploy"
    branches: master
    agents:
      queue: elastic

  - wait

  - name: ":shipit: Deploy NPM Package"
    command: "docker-compose run --rm build bin/staging"
    branches: master
    agents:
      queue: elastic

  - wait

  - name: ":loudspeaker: Announce It"
    command: "./bin/announce"
    branches: master
    agents:
      queue: elastic
